// ===============================================
//  App.js (FINAL CLEAN + UPDATED)
// ===============================================

import React from "react";
import { NavigationContainer } from "@react-navigation/native";
import { createStackNavigator } from "@react-navigation/stack";
import { createBottomTabNavigator } from "@react-navigation/bottom-tabs";
import { Ionicons } from "@expo/vector-icons";

import { KeyboardProvider } from "react-native-keyboard-controller";

import { AuthProvider, useAuth } from "./contexts/AuthContext";
import { colors } from "./colors";

/* ---------------------- Doctor Screens ---------------------- */
import AddPatient from "./screens/AddPatient";
import DoctorDashboard from "./screens/DoctorDashboard";
import PatientManagement from "./screens/PatientManagement";
import PatientProfile from "./screens/PatientProfile";
import EditPatient from "./screens/EditPatient";
import FoodDatabase from "./screens/FoodDatabase";
import AddFoodScreen from "./screens/AddFoodScreen";
import DietPlans from "./screens/DietPlans";
import Reports from "./screens/Reports";
import Collections from "./screens/Collections";
import Recipes from "./screens/Recipes";
import DietChart from "./screens/DietChart";
import AutoGenerateDiet from "./screens/AutoGenerateDiet";
import Settings from "./screens/Settings";
import EditUserProfile from "./screens/EditUserProfile";
import PatientDashboard from "./screens/PatientDashboard";
import ChangePassword from "./screens/ChangePassword";

/* ---------------------- Patient Screens ---------------------- */
import DietHistory from "./screens/DietHistory";
import Reminders from "./screens/Reminders";
import PatientSettings from "./screens/PatientSettings";

/* ---------------------- Chat Screens ---------------------- */
import ChatList from "./screens/ChatList";
import ChatScreen from "./screens/ChatScreen";

/* ---------------------- Common ---------------------- */
import LoginPage from "./screens/LoginPage";

const Stack = createStackNavigator();
const Tab = createBottomTabNavigator();

/* ---------------------- DOCTOR TABS ---------------------- */
function DoctorTabs() {
  return (
    <Tab.Navigator
      screenOptions={{
        tabBarActiveTintColor: colors.primary,
        tabBarInactiveTintColor: colors.foregroundLight,
        tabBarStyle: { backgroundColor: colors.card },
      }}
    >
      <Tab.Screen
        name="Dashboard"
        component={DoctorDashboard}
        options={{
          tabBarIcon: ({ color, size }) => (
            <Ionicons name="speedometer-outline" color={color} size={size} />
          ),
        }}
      />

      <Tab.Screen
        name="Patients"
        component={PatientManagement}
        options={{
          tabBarIcon: ({ color, size }) => (
            <Ionicons name="people-outline" color={color} size={size} />
          ),
        }}
      />

      <Tab.Screen
        name="Chat"
        component={ChatList}
        options={{
          headerShown: false,
          tabBarIcon: ({ color, size }) => (
            <Ionicons name="chatbubble-ellipses-outline" color={color} size={size} />
          ),
        }}
      />

      <Tab.Screen
        name="FoodDatabase"
        component={FoodDatabase}
        options={{
          tabBarIcon: ({ color, size }) => (
            <Ionicons name="restaurant-outline" color={color} size={size} />
          ),
        }}
      />

      <Tab.Screen
        name="Settings"
        component={Settings}
        options={{
          headerShown: false,
          tabBarIcon: ({ color, size }) => (
            <Ionicons name="settings-outline" color={color} size={size} />
          ),
        }}
      />
    </Tab.Navigator>
  );
}

/* ---------------------- PATIENT TABS ---------------------- */
function PatientTabs() {
  return (
    <Tab.Navigator
      screenOptions={{
        tabBarActiveTintColor: colors.primary,
        tabBarInactiveTintColor: colors.foregroundLight,
        tabBarStyle: { backgroundColor: colors.card },
      }}
    >
      <Tab.Screen
        name="Dashboard"
        component={PatientDashboard}
        options={{
          tabBarIcon: ({ color, size }) => (
            <Ionicons name="home-outline" color={color} size={size} />
          ),
        }}
      />

      <Tab.Screen
        name="DietHistory"
        component={DietHistory}
        options={{
          tabBarIcon: ({ color, size }) => (
            <Ionicons name="nutrition-outline" color={color} size={size} />
          ),
        }}
      />

      <Tab.Screen
        name="Chat"
        component={ChatList}
        options={{
          headerShown: false,
          tabBarIcon: ({ color, size }) => (
            <Ionicons name="chatbubble-outline" color={color} size={size} />
          ),
        }}
      />

      <Tab.Screen
        name="Reminders"
        component={Reminders}
        options={{
          tabBarIcon: ({ color, size }) => (
            <Ionicons name="alarm-outline" color={color} size={size} />
          ),
        }}
      />

      <Tab.Screen
        name="Settings"
        component={PatientSettings}
        options={{
          headerShown: false,
          tabBarIcon: ({ color, size }) => (
            <Ionicons name="settings-outline" color={color} size={size} />
          ),
        }}
      />
    </Tab.Navigator>
  );
}

/* ---------------------- MAIN NAVIGATION ---------------------- */
function AppNavigator() {
  const { isAuthenticated, isLoading, user } = useAuth();

  if (isLoading) return null;

  return (
    <NavigationContainer>
      <Stack.Navigator screenOptions={{ headerShown: false }}>
        {!isAuthenticated ? (
          <Stack.Screen name="Login" component={LoginPage} />
        ) : user?.role === "PATIENT" ? (
          <>
            <Stack.Screen name="MainTabs" component={PatientTabs} />

            {/* CHAT */}
            <Stack.Screen
              name="ChatList"
              component={ChatList}
              options={{ headerShown: false }}  // ✅ FIXED
            />
            <Stack.Screen
              name="ChatScreen"
              component={ChatScreen}
              options={({ route }) => ({
                headerShown: true,
                title: route.params?.patientName,
              })}
            />

            {/* PATIENT SETTINGS */}
            <Stack.Screen
              name="PatientSettings"
              component={PatientSettings}
              options={{ headerShown: false }}
            />

            <Stack.Screen
              name="ChangePassword"
              component={ChangePassword}
              options={{ headerShown: true, title: "Change Password" }}
            />

            <Stack.Screen
              name="EditUserProfile"
              component={EditUserProfile}
              options={{ headerShown: true, title: "Edit Profile" }}
            />
          </>
        ) : (
          <>
            <Stack.Screen name="MainTabs" component={DoctorTabs} />

            {/* CHAT */}
            <Stack.Screen
              name="ChatList"
              component={ChatList}
              options={{ headerShown: false }}  // ✅ FIXED
            />
            <Stack.Screen
              name="ChatScreen"
              component={ChatScreen}
              options={({ route }) => ({
                headerShown: true,
                title: route.params?.patientName,
              })}
            />

            {/* PATIENT MGMT */}
            <Stack.Screen
              name="PatientProfile"
              component={PatientProfile}
              options={{ headerShown: true }}
            />
            <Stack.Screen
              name="EditPatient"
              component={EditPatient}
              options={{ headerShown: true }}
            />
            <Stack.Screen
              name="AddPatient"
              component={AddPatient}
              options={{ headerShown: true, title: "Add New Patient" }}
            />

            {/* DIET */}
            <Stack.Screen name="DietPlans" component={DietPlans} />
            <Stack.Screen name="Collections" component={Collections} />
            <Stack.Screen name="Recipes" component={Recipes} />
            <Stack.Screen name="DietChart" component={DietChart} />
            <Stack.Screen name="AutoGenerateDiet" component={AutoGenerateDiet} />

            <Stack.Screen
              name="AddFoodScreen"
              component={AddFoodScreen}
              options={{ headerShown: true, title: "Add New Food" }}
            />

            {/* DOCTOR SETTINGS */}
            <Stack.Screen
              name="ChangePassword"
              component={ChangePassword}
              options={{ headerShown: true, title: "Change Password" }}
            />

            <Stack.Screen
              name="EditUserProfile"
              component={EditUserProfile}
              options={{ headerShown: true, title: "Edit Profile" }}
            />
          </>
        )}
      </Stack.Navigator>
    </NavigationContainer>
  );
}

/* ---------------------- ROOT WRAPPER ---------------------- */
export default function App() {
  return (
    <AuthProvider>
      <KeyboardProvider>
        <AppNavigator />
      </KeyboardProvider>
    </AuthProvider>
  );
}
