// ===============================================
//  App.js — FINAL (Doctor + Patient + Admin + Botpress Chat)
// ===============================================

import React from "react";
import { TouchableOpacity } from "react-native";
import { NavigationContainer } from "@react-navigation/native";
import { createStackNavigator } from "@react-navigation/stack";
import { createBottomTabNavigator } from "@react-navigation/bottom-tabs";
import { Ionicons } from "@expo/vector-icons";
import { KeyboardProvider } from "react-native-keyboard-controller";
import { AuthProvider, useAuth } from "./contexts/AuthContext";
import { colors } from "./colors";
import RecipeScreen from "./screens/patient/RecipeScreen";

/* ---------------------- Doctor Screens ---------------------- */
import AddPatient from "./screens/doctor/AddPatient";
import DoctorDashboard from "./screens/doctor/DoctorDashboard";
import PatientManagement from "./screens/doctor/PatientManagement";
import PatientProfile from "./screens/doctor/PatientProfile";
import EditPatient from "./screens/doctor/EditPatient";
import FoodDatabase from "./screens/doctor/FoodDatabase";
import AddFoodScreen from "./screens/doctor/AddFoodScreen";
import Collections from "./screens/doctor/Collections";
import Recipes from "./screens/doctor/Recipes";
import Settings from "./screens/doctor/Settings";
import EditUserProfile from "./screens/doctor/EditUserProfile";
import DietChartsList from "./screens/doctor/DietChartsList";
import CreateDietChart from "./screens/doctor/CreateDietChart";
import EditDietDay from "./screens/doctor/EditDietDay";

/* ---------------------- Patient Screens ---------------------- */
import PatientDashboard from "./screens/patient/PatientDashboard";
import AutoGenerateDiet from "./screens/patient/AutoGenerateDiet";
import DietChart from "./screens/patient/DietChart";
import DietHistory from "./screens/patient/DietHistory";
import Reminders from "./screens/patient/Reminders";
import PatientSettings from "./screens/patient/PatientSettings";
import ChatEntryForPatient from "./screens/patient/ChatEntryForPatient";

/* ---------------------- Admin Screens ---------------------- */
import AdminDashboard from "./screens/admin/AdminDashboard";
import DoctorAuthentication from "./screens/admin/DoctorAuthentication";

/* ---------------------- Chat Screens (Common) ---------------------- */
import ChatList from "./screens/doctor/ChatList";
import ChatScreen from "./screens/common/ChatScreen";

/* ---------------------- Common Screens ---------------------- */
import LoginPage from "./screens/common/LoginPage";
import ChangePassword from "./screens/common/ChangePassword";
import WaitingVerification from "./screens/common/WaitingVerification";

import "./src/i18n";

/* ---------------------- ⭐ Botpress Chat UI Screen ---------------------- */
import BotpressChatScreen from "./screens/BotpressChatScreen";

const Stack = createStackNavigator();
const Tab = createBottomTabNavigator();

/* ---------------------- HEADER CHAT BUTTON ---------------------- */
function chatHeaderButton(navigation) {
  return (
    <TouchableOpacity
      onPress={() => navigation.navigate("ChatEntry")}
      style={{
        marginRight: 16,
        backgroundColor: colors.primary,
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: "center",
        justifyContent: "center",
      }}
    >
      <Ionicons name="chatbubble-ellipses" size={20} color="#fff" />
    </TouchableOpacity>
  );
}

/* ---------------------- ADMIN TABS ---------------------- */
function AdminTabs() {
  return (
    <Tab.Navigator
      screenOptions={{ tabBarActiveTintColor: colors.primary, headerShown: false }}
    >
      <Tab.Screen
        name="AdminDashboard"
        component={AdminDashboard}
        options={{
          title: "Dashboard",
          tabBarIcon: ({ color, size }) => (
            <Ionicons name="grid-outline" color={color} size={size} />
          ),
        }}
      />

      <Tab.Screen
        name="DoctorAuthentication"
        component={DoctorAuthentication}
        options={{
          title: "Doctors",
          tabBarIcon: ({ color, size }) => (
            <Ionicons name="medkit-outline" color={color} size={size} />
          ),
        }}
      />
    </Tab.Navigator>
  );
}

/* ---------------------- DOCTOR TABS ---------------------- */
function DoctorTabs() {
  return (
    <Tab.Navigator
      screenOptions={({ navigation }) => ({
        tabBarActiveTintColor: colors.primary,
        headerRight: () => chatHeaderButton(navigation),
      })}
    >
      <Tab.Screen
        name="Dashboard"
        component={DoctorDashboard}
        options={{
          tabBarIcon: ({ color, size }) => (
            <Ionicons name="speedometer-outline" color={color} size={size} />
          ),
        }}
      />
      <Tab.Screen
        name="DietCharts"
        component={DietChartsList}
        options={{
          title: "Diet Charts",
          tabBarIcon: ({ color, size }) => (
            <Ionicons name="document-text-outline" color={color} size={size} />
          ),
        }}
      />
      <Tab.Screen
        name="Patients"
        component={PatientManagement}
        options={{
          tabBarIcon: ({ color, size }) => (
            <Ionicons name="people-outline" color={color} size={size} />
          ),
        }}
      />
      <Tab.Screen
        name="FoodDatabase"
        component={FoodDatabase}
        options={{
          tabBarIcon: ({ color, size }) => (
            <Ionicons name="restaurant-outline" color={color} size={size} />
          ),
        }}
      />
      <Tab.Screen
        name="Settings"
        component={Settings}
        options={{
          headerShown: false,
          tabBarIcon: ({ color, size }) => (
            <Ionicons name="settings-outline" color={color} size={size} />
          ),
        }}
      />
    </Tab.Navigator>
  );
}

/* ---------------------- PATIENT TABS ---------------------- */
function PatientTabs() {
  return (
    <Tab.Navigator
      screenOptions={({ navigation }) => ({
        tabBarActiveTintColor: colors.primary,
        headerRight: () => chatHeaderButton(navigation),
      })}
    >
      <Tab.Screen
        name="Dashboard"
        component={PatientDashboard}
        options={{
          tabBarIcon: ({ color, size }) => (
            <Ionicons name="home-outline" color={color} size={size} />
          ),
        }}
      />

      <Tab.Screen
        name="MyPlan"
        component={DietChart}
        options={{
          title: "My Plan",
          tabBarIcon: ({ color, size }) => (
            <Ionicons name="list-outline" color={color} size={size} />
          ),
        }}
      />

      <Tab.Screen
        name="Reminders"
        component={Reminders}
        options={{
          tabBarIcon: ({ color, size }) => (
            <Ionicons name="alarm-outline" color={color} size={size} />
          ),
        }}
      />

      <Tab.Screen
        name="Recipes"
        component={RecipeScreen}
        options={{
          title: "Recipes",
          tabBarIcon: ({ color, size }) => (
            <Ionicons name="leaf-outline" color={color} size={size} />
          ),
        }}
      />

      <Tab.Screen
        name="Settings"
        component={PatientSettings}
        options={{
          headerShown: false,
          tabBarIcon: ({ color, size }) => (
            <Ionicons name="settings-outline" color={color} size={size} />
          ),
        }}
      />
    </Tab.Navigator>
  );
}

/* ---------------------- MAIN NAVIGATOR ---------------------- */
function AppNavigator() {
  const { isAuthenticated, isLoading, user } = useAuth();

  if (isLoading) return null;

  return (
    <NavigationContainer>
      <Stack.Navigator screenOptions={{ headerShown: false }}>

        {/* ========== NOT AUTHENTICATED ROUTES ========== */}
        {!isAuthenticated ? (
          <>
            <Stack.Screen name="Login" component={LoginPage} />

            <Stack.Screen
              name="WaitingVerification"
              component={WaitingVerification}
              options={{
                headerShown: true,
                title: "Verification Pending",
                headerStyle: { backgroundColor: colors.card },
                headerTintColor: colors.foreground,
              }}
            />
          </>
        ) : user?.role === "SUPER_ADMIN" ? (
          <>
            <Stack.Screen name="AdminMain" component={AdminTabs} />
            <Stack.Screen name="ChatEntry" component={ChatList} />
            <Stack.Screen name="ChatScreen" component={ChatScreen} />
          </>
        ) : user?.role === "PATIENT" ? (
          <>
            <Stack.Screen name="MainTabs" component={PatientTabs} />

            <Stack.Screen name="DietChart" component={DietChart} />

            <Stack.Screen
              name="ChatEntry"
              component={ChatEntryForPatient}
              options={{
                headerShown: true,
                title: "Messages",
              }}
            />

            <Stack.Screen name="ChatScreen" component={ChatScreen} />
            <Stack.Screen name="PatientSettings" component={PatientSettings} />
            <Stack.Screen name="ChangePassword" component={ChangePassword} />
            <Stack.Screen name="EditUserProfile" component={EditUserProfile} />
            <Stack.Screen name="AutoGenerateDiet" component={AutoGenerateDiet} />
          </>
        ) : (
          <>
            <Stack.Screen name="MainTabs" component={DoctorTabs} />

            <Stack.Screen name="ChatEntry" component={ChatList} />

            <Stack.Screen
              name="EditDietDay"
              component={EditDietDay}
              options={{ headerShown: true, title: "Edit Day" }}
            />

            <Stack.Screen
              name="CreateDietChart"
              component={CreateDietChart}
              options={{ headerShown: true, title: "Diet Chart" }}
            />

            <Stack.Screen name="ChatScreen" component={ChatScreen} />
            <Stack.Screen name="PatientProfile" component={PatientProfile} />
            <Stack.Screen name="EditPatient" component={EditPatient} />
            <Stack.Screen name="AddPatient" component={AddPatient} />
            <Stack.Screen name="Collections" component={Collections} />
            <Stack.Screen name="Recipes" component={Recipes} />
            <Stack.Screen name="DietChart" component={DietChart} />
            <Stack.Screen name="AutoGenerateDiet" component={AutoGenerateDiet} />
            <Stack.Screen name="AddFoodScreen" component={AddFoodScreen} />
            <Stack.Screen name="ChangePassword" component={ChangePassword} />
            <Stack.Screen name="EditUserProfile" component={EditUserProfile} />
          </>
        )}

        {/* ⭐ GLOBAL BOTPRESS CHAT SCREEN - AVAILABLE TO ALL ROLES */}
        <Stack.Screen
          name="BotpressChat"
          component={BotpressChatScreen}
          options={{
            headerShown: true,
            title: "AyurBot AI",
            headerStyle: { backgroundColor: "#fff" },
            headerTintColor: colors.primary,
          }}
        />

      </Stack.Navigator>
    </NavigationContainer>
  );
}

export default function App() {
  return (
    <AuthProvider>
      <KeyboardProvider>
        <AppNavigator />
      </KeyboardProvider>
    </AuthProvider>
  );
}
