// ===============================================
//  App.js — FINAL (Doctor + Patient + Header Chat)
// ===============================================

import React from "react";
import {
  TouchableOpacity
} from "react-native";
import { NavigationContainer } from "@react-navigation/native";
import { createStackNavigator } from "@react-navigation/stack";
import { createBottomTabNavigator } from "@react-navigation/bottom-tabs";
import { Ionicons } from "@expo/vector-icons";

import { KeyboardProvider } from "react-native-keyboard-controller";

import { AuthProvider, useAuth } from "./contexts/AuthContext";
import { colors } from "./colors";

/* ---------------------- Doctor Screens ---------------------- */
import AddPatient from "./screens/doctor/AddPatient";
import DoctorDashboard from "./screens/doctor/DoctorDashboard";
import PatientManagement from "./screens/doctor/PatientManagement";
import PatientProfile from "./screens/doctor/PatientProfile";
import EditPatient from "./screens/doctor/EditPatient";
import FoodDatabase from "./screens/doctor/FoodDatabase";
import AddFoodScreen from "./screens/doctor/AddFoodScreen";
import Collections from "./screens/doctor/Collections";
import Recipes from "./screens/doctor/Recipes";
import Settings from "./screens/doctor/Settings";
import EditUserProfile from "./screens/doctor/EditUserProfile";
import DietChartsList from "./screens/doctor/DietChartsList";
import CreateDietChart from "./screens/doctor/CreateDietChart";
import EditDietDay from "./screens/doctor/EditDietDay";




/* ---------------------- Patient Screens ---------------------- */
import PatientDashboard from "./screens/patient/PatientDashboard";
import AutoGenerateDiet from "./screens/patient/AutoGenerateDiet";
import DietChart from "./screens/patient/DietChart";
import DietHistory from "./screens/patient/DietHistory";
import Reminders from "./screens/patient/Reminders";
import Reports from "./screens/patient/Reports";
import PatientSettings from "./screens/patient/PatientSettings";

/* ---- SPECIAL: Chat entry for patient (direct doctor chat) ---- */
import ChatEntryForPatient from "./screens/patient/ChatEntryForPatient";

/* ---------------------- Chat Screens (Common) ---------------------- */
import ChatList from "./screens/doctor/ChatList"; // doctor chat list
import ChatScreen from "./screens/common/ChatScreen";

/* ---------------------- Common Screens ---------------------- */
import LoginPage from "./screens/common/LoginPage";
import ChangePassword from "./screens/common/ChangePassword";

const Stack = createStackNavigator();
const Tab = createBottomTabNavigator();

/* ---------------------- HEADER CHAT BUTTON ---------------------- */
function chatHeaderButton(navigation) {
  return (
    <TouchableOpacity
      onPress={() => navigation.navigate("ChatEntry")}
      style={{
        marginRight: 16,
        backgroundColor: colors.primary,
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: "center",
        justifyContent: "center",
        shadowColor: "#000",
        shadowOpacity: 0.15,
        shadowOffset: { width: 0, height: 2 },
        elevation: 4,
      }}
    >
      <Ionicons name="chatbubble-ellipses" size={20} color="#fff" />
    </TouchableOpacity>
  );
}

/* ---------------------- DOCTOR TABS ---------------------- */
function DoctorTabs() {
  return (
    <Tab.Navigator
      screenOptions={({ navigation }) => ({
        tabBarActiveTintColor: colors.primary,
        tabBarInactiveTintColor: colors.foregroundLight,
        tabBarStyle: { backgroundColor: colors.card },

        // ⭐ HEADER CHAT BUTTON
        headerRight: () => chatHeaderButton(navigation),
      })}
    >
      <Tab.Screen
        name="Dashboard"
        component={DoctorDashboard}
        options={{
          tabBarIcon: ({ color, size }) => (
            <Ionicons name="speedometer-outline" color={color} size={size} />
          ),
        }}
      />

      <Tab.Screen
        name="DietCharts"
        component={DietChartsList}
        options={{
          tabBarIcon: ({ color, size }) => (
            <Ionicons name="document-text-outline" color={color} size={size} />
          ),
          title: "Diet Charts",
        }}
      />


      <Tab.Screen
        name="Patients"
        component={PatientManagement}
        options={{
          tabBarIcon: ({ color, size }) => (
            <Ionicons name="people-outline" color={color} size={size} />
          ),
        }}
      />

      <Tab.Screen
        name="FoodDatabase"
        component={FoodDatabase}
        options={{
          tabBarIcon: ({ color, size }) => (
            <Ionicons name="restaurant-outline" color={color} size={size} />
          ),
        }}
      />

      <Tab.Screen
        name="Settings"
        component={Settings}
        options={{
          headerShown: false,
          tabBarIcon: ({ color, size }) => (
            <Ionicons name="settings-outline" color={color} size={size} />
          ),
        }}
      />
    </Tab.Navigator>
  );
}

/* ---------------------- PATIENT TABS ---------------------- */
function PatientTabs() {
  return (
    <Tab.Navigator
      screenOptions={({ navigation }) => ({
        tabBarActiveTintColor: colors.primary,
        tabBarInactiveTintColor: colors.foregroundLight,
        tabBarStyle: { backgroundColor: colors.card },

        // ⭐ HEADER CHAT BUTTON
        headerRight: () => chatHeaderButton(navigation),
      })}
    >
      <Tab.Screen
        name="Dashboard"
        component={PatientDashboard}
        options={{
          tabBarIcon: ({ color, size }) => (
            <Ionicons name="home-outline" color={color} size={size} />
          ),
        }}
      />

      <Tab.Screen
        name="DietHistory"
        component={DietHistory}
        options={{
          tabBarIcon: ({ color, size }) => (
            <Ionicons name="nutrition-outline" color={color} size={size} />
          ),
        }}
      />

      <Tab.Screen
        name="Reminders"
        component={Reminders}
        options={{
          tabBarIcon: ({ color, size }) => (
            <Ionicons name="alarm-outline" color={color} size={size} />
          ),
        }}
      />

      <Tab.Screen
        name="Settings"
        component={PatientSettings}
        options={{
          headerShown: false,
          tabBarIcon: ({ color, size }) => (
            <Ionicons name="settings-outline" color={color} size={size} />
          ),
        }}
      />
    </Tab.Navigator>
  );
}

/* ---------------------- MAIN NAVIGATOR ---------------------- */
function AppNavigator() {
  const { isAuthenticated, isLoading, user } = useAuth();

  if (isLoading) return null;

  return (
    <NavigationContainer>
      <Stack.Navigator screenOptions={{ headerShown: false }}>

        {!isAuthenticated ? (
          <Stack.Screen name="Login" component={LoginPage} />
        ) : user?.role === "PATIENT" ? (
          <>
            <Stack.Screen name="MainTabs" component={PatientTabs} />

            {/* UNIVERSAL CHAT ENTRY */}
            <Stack.Screen
              name="ChatEntry"
              component={ChatEntryForPatient}
              options={{
                headerShown: true,
                title: "Messages",
                headerStyle: { backgroundColor: colors.card },
                headerTintColor: colors.foreground,
              }}
            />

            <Stack.Screen
              name="ChatScreen"
              component={ChatScreen}
              options={{
                headerShown: true,
                headerStyle: { backgroundColor: colors.card },
                headerTintColor: colors.foreground,
              }}
            />

            <Stack.Screen
              name="PatientSettings"
              component={PatientSettings}
              options={{ headerShown: false }}
            />

            <Stack.Screen
              name="ChangePassword"
              component={ChangePassword}
              options={{ headerShown: true, title: "Change Password" }}
            />

            <Stack.Screen
              name="EditUserProfile"
              component={EditUserProfile}
              options={{ headerShown: true, title: "Edit Profile" }}
            />
          </>
        ) : (
          <>
            <Stack.Screen name="MainTabs" component={DoctorTabs} />

            {/* UNIVERSAL CHAT ENTRY */}
            <Stack.Screen
              name="ChatEntry"
              component={ChatList}
              options={{
                headerShown: true,
                title: "Messages",
                headerStyle: { backgroundColor: colors.card },
                headerTintColor: colors.foreground,
              }}
            />

            <Stack.Screen
              name="EditDietDay"
              component={EditDietDay}
              options={{
                headerShown: true,
                title: "Edit Day",
                headerStyle: { backgroundColor: colors.card },
                headerTintColor: colors.foreground,
              }}
            />


            <Stack.Screen
              name="CreateDietChart"
              component={CreateDietChart}
              options={{
                headerShown: true,
                title: "Diet Chart",
                headerStyle: { backgroundColor: colors.card },
                headerTintColor: colors.foreground,
              }}
            />


            <Stack.Screen
              name="ChatScreen"
              component={ChatScreen}
              options={{
                headerShown: true,
                headerStyle: { backgroundColor: colors.card },
                headerTintColor: colors.foreground,
              }}
            />

            {/* PATIENT MGMT */}
            <Stack.Screen name="PatientProfile" component={PatientProfile} />
            <Stack.Screen name="EditPatient" component={EditPatient} />
            <Stack.Screen
              name="AddPatient"
              component={AddPatient}
              options={{ headerShown: true, title: "Add New Patient" }}
            />

            {/* DIET */}
            <Stack.Screen name="Collections" component={Collections} />
            <Stack.Screen name="Recipes" component={Recipes} />
            <Stack.Screen name="DietChart" component={DietChart} />
            <Stack.Screen name="AutoGenerateDiet" component={AutoGenerateDiet} />
            <Stack.Screen
              name="AddFoodScreen"
              component={AddFoodScreen}

            />

            {/* SETTINGS */}
            <Stack.Screen
              name="ChangePassword"
              component={ChangePassword}
              options={{ headerShown: true, title: "Change Password" }}
            />

            <Stack.Screen
              name="EditUserProfile"
              component={EditUserProfile}
              options={{ headerShown: true, title: "Edit Profile" }}
            />
          </>
        )}
      </Stack.Navigator>
    </NavigationContainer>
  );
}

/* ---------------------- ROOT WRAPPER ---------------------- */
export default function App() {
  return (
    <AuthProvider>
      <KeyboardProvider>
        <AppNavigator />
      </KeyboardProvider>
    </AuthProvider>
  );
}
