import React, { useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TextInput,
  TouchableOpacity,
  Alert,
  ActivityIndicator,
} from 'react-native';
import { colors } from '../../colors';
import { dietPlansAPI } from '../../services/api';

export default function AutoGenerateDiet({ navigation }) {
  const [formData, setFormData] = useState({
    patientId: '',
    name: '',
    duration: '',
    description: '',
  });
  const [loading, setLoading] = useState(false);

  const handleGenerate = async () => {
    if (!formData.patientId || !formData.name || !formData.duration) {
      Alert.alert('Error', 'Please fill in all required fields');
      return;
    }

    try {
      setLoading(true);
      const payload = {
        ...formData,
        duration: Number(formData.duration),
      };
      await dietPlansAPI.create(payload);
      Alert.alert('Success', 'Diet plan generated successfully!');
      navigation?.goBack();
    } catch (error) {
      Alert.alert('Error', error.response?.data?.message || 'Failed to generate diet plan');
    } finally {
      setLoading(false);
    }
  };

  return (
    <ScrollView style={styles.container}>
      <View style={styles.header}>
        <Text style={styles.title}>Auto Generate Diet</Text>
        <Text style={styles.subtitle}>Create a new diet plan automatically</Text>
      </View>

      <View style={styles.form}>
        <View style={styles.inputGroup}>
          <Text style={styles.label}>Patient ID *</Text>
          <TextInput
            style={styles.input}
            value={formData.patientId}
            onChangeText={(text) => setFormData({ ...formData, patientId: text })}
            placeholder="Enter patient ID"
            placeholderTextColor={colors.foregroundLight}
          />
        </View>

        <View style={styles.inputGroup}>
          <Text style={styles.label}>Diet Plan Name *</Text>
          <TextInput
            style={styles.input}
            value={formData.name}
            onChangeText={(text) => setFormData({ ...formData, name: text })}
            placeholder="Enter diet plan name"
            placeholderTextColor={colors.foregroundLight}
          />
        </View>

        <View style={styles.inputGroup}>
          <Text style={styles.label}>Duration (days) *</Text>
          <TextInput
            style={styles.input}
            value={formData.duration}
            onChangeText={(text) => setFormData({ ...formData, duration: text })}
            keyboardType="numeric"
            placeholder="Enter duration in days"
            placeholderTextColor={colors.foregroundLight}
          />
        </View>

        <View style={styles.inputGroup}>
          <Text style={styles.label}>Description</Text>
          <TextInput
            style={[styles.input, styles.textArea]}
            value={formData.description}
            onChangeText={(text) => setFormData({ ...formData, description: text })}
            multiline
            numberOfLines={4}
            placeholder="Enter description (optional)"
            placeholderTextColor={colors.foregroundLight}
          />
        </View>

        <TouchableOpacity
          style={[styles.button, loading && styles.buttonDisabled]}
          onPress={handleGenerate}
          disabled={loading}
        >
          {loading ? (
            <ActivityIndicator color="#FFFFFF" />
          ) : (
            <Text style={styles.buttonText}>Generate Diet Plan</Text>
          )}
        </TouchableOpacity>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    padding: 20,
    backgroundColor: colors.card,
    marginBottom: 16,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.foreground,
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 14,
    color: colors.foregroundLight,
  },
  form: {
    padding: 16,
  },
  inputGroup: {
    marginBottom: 20,
  },
  label: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.foreground,
    marginBottom: 8,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    backgroundColor: colors.backgroundLight,
    color: colors.foreground,
  },
  textArea: {
    height: 100,
    textAlignVertical: 'top',
  },
  button: {
    backgroundColor: colors.primary,
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 8,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
});

